// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


int free_parking_slot_1_int;
int free_parking_slot_2_int;
int parkedVehiclesCount;
int timed_parking_slot_1_int;
int timed_parking_slot_2_int;
bool free_parking_slot_1;
bool free_parking_slot_2;
bool timed_parking_slot_1;
bool timed_parking_slot_2;

void initProperties(){

  ArduinoCloud.addProperty(free_parking_slot_1_int, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(free_parking_slot_2_int, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(parkedVehiclesCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timed_parking_slot_1_int, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timed_parking_slot_2_int, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(free_parking_slot_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(free_parking_slot_2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timed_parking_slot_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(timed_parking_slot_2, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);